version: '3.4'

services:
  account.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Server=tcp:${PANDALOGIX_DATABASE};Database=panda;User Id=sa;Password=yourStrong!Password;
      # ports:
    #   - "7794:80"
  engine.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Server=tcp:${PANDALOGIX_DATABASE};Database=panda;User Id=sa;Password=yourStrong!Password;
    # ports:
    #   - "29308:80"

  padmanager.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Server=tcp:${PANDALOGIX_DATABASE};Database=panda;User Id=sa;Password=yourStrong!Password;
  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceEndPoints__AccountService=http://${PANDALOGIX_ACCOUNTSERVICE}/api/account/
      - ServiceEndPoints__PadManagerService=http://${PANDALOGIX_PADMANGERSERVICE}/api/pad/
      - ServiceEndPoints__EngineService=http://${PANDALOGIX_ENGINESERVICE}/api/engine/
    ports:
      - 80

networks:
  default:
    driver: bridge