version: '3.4'

services:
  account.service:
    image: ${DOCKER_REGISTRY}accountservice
    container_name: ${PANDALOGIX_ACCOUNTSERVICE}
    build:
      context: .
      dockerfile: AccountManager/Account.Service/Dockerfile
    depends_on:
      - db
  engine.service:
    image: ${DOCKER_REGISTRY}engineservice
    container_name: ${PANDALOGIX_ENGINESERVICE}
    build:
      context: .
      dockerfile: Engine/Engine.Service/Dockerfile
    depends_on:
      - db
  padmanager.service:
    image: ${DOCKER_REGISTRY}padservice
    container_name: ${PANDALOGIX_PADMANGERSERVICE}
    build:
      context: .
      dockerfile: PadManager/PadManager.Service/Dockerfile
    depends_on:
      - db

  webspa:
    image: ${DOCKER_REGISTRY}webspa
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
    depends_on:
      - account.service
      - engine.service

  db:
    image: ${DOCKER_REGISTRY}datbase
    container_name: ${PANDALOGIX_DATABASE}
    build:
      context: ./Database
      dockerfile: Dockerfile
