version: '3.4'

services:
  account.service:
    image: accountservice:dev
    build:
      target: build
    volumes:
       - ./vsblg:/vsdbg
    entrypoint: ["dotnet", "/app/Account.Service.dll"]
  engine.service:
    image: engineservice:dev
    build:
      target: build
    volumes:
       - ./vsblg:/vsdbg
    entrypoint: ["dotnet", "/app/Engine.Service.dll"]
  padmanager.service:
    image: padmanager:dev
    build:
      target: build
    volumes:
       - ./vsblg:/vsdbg
    entrypoint: ["dotnet", "/app/PadMnager.Service.dll"]
  webspa:
    image: webspa:dev
    build:
      target: build
    volumes:
       - ./vsblg:/vsdbg
    entrypoint: ["dotnet", "/app/WebSPA.dll"]
