version: '3.4'

services:
  account.service:
    image: ${DOCKER_REGISTRY}accountservice
    container_name: ${PANDALOGIX_ACCOUNTSERVICE}
    depends_on:
      - db
  engine.service:
    image: ${DOCKER_REGISTRY}engineservice
    container_name: ${PANDALOGIX_ENGINESERVICE}
    depends_on:
      - db
  padmanager.service:
    image: ${DOCKER_REGISTRY}padservice
    container_name: ${PANDALOGIX_PADMANGERSERVICE}
    depends_on:
      - db

  webspa:
    image: ${DOCKER_REGISTRY}webspa
    ports:
      - "5000:80"
    depends_on:
      - account.service
      - engine.service

  db:
    image: ${DOCKER_REGISTRY}datbase
    container_name: ${PANDALOGIX_DATABASE}

