version: '3.4'

services:
  account.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7794:80"
  engine.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "29308:80"
  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

