version: '3.4'

services:
  account.service:
    image: ${DOCKER_REGISTRY}accountservice
    build:
      context: .
      dockerfile: AccountManager/Account.Service/Dockerfile
    depends_on:
      - db
  engine.service:
    image: ${DOCKER_REGISTRY}engineservice
    build:
      context: .
      dockerfile: Engine/Engine.Service/Dockerfile
    depends_on:
      - db

  webspa:
    image: ${DOCKER_REGISTRY}webspa
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
    depends_on:
      - account.service
      - engine.service

  db:
    image: ${DOCKER_REGISTRY}datbase
    build:
      context: ./Database
      dockerfile: Dockerfile
